apiVersion: v1
kind: Service
metadata:
  name: postgres-db-np
spec:
  selector:
    app: postgresql-db
  type: NodePort
  ports:
    - name: pg-port
      port: 5432
      nodePort: 30032
      protocol: TCP
      targetPort: 5432
    - name: pg-exporter-port
      port: 9187
      nodePort: 30087
      protocol: TCP
      targetPort: 9187
