apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgresql-db
  ports:
    - name: pg-port
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: pg-exporter-port
      port: 9187
      protocol: TCP
      targetPort: 9187
